kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-cluster
nodes:
- role: worker
  extraMounts:
  - hostPath: /tmp/kube-storage/worker1
    containerPath: /var/openebs/local/
- role: worker
  extraMounts:
  - hostPath: /tmp/kube-storage/worker2
    containerPath: /var/openebs/local/
- role: worker
  extraMounts:
  - hostPath: /tmp/kube-storage/worker3
    containerPath: /var/openebs/local/
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
    - containerPort: 32080
      hostPort: 80
      protocol: TCP
    - containerPort: 32443
      hostPort: 443
      protocol: TCP
    - containerPort: 32090
      hostPort: 9000
      protocol: TCP
  # extraMounts:
  #   - hostPath: /tmp/kind/exports/
  #     containerPath: /exports
