---
additionalArguments:
    - --accesslog=true
    - --log.level=DEBUG

providers:
  kubernetesCRD:
    namespaces:
      - default
      - traefik
  kubernetesIngress:
    namespaces:
      - default
      - traefik
      - uat
      - prod

ports:
  traefik:
    expose: true
    nodePort: 32090
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443

service:
  type: NodePort
