# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
---
additionalArguments:
  - --accesslog=true
  - --log.level=DEBUG

providers:
  kubernetesCRD:
    namespaces:
      - default
      - traefik
  kubernetesIngress:
    namespaces:
      - default
      - traefik
      - uat
      - prod

# Configure ports
ports:
  traefik:
    expose: true

# DaemonSet here is used to provide high availibility traefik
# It has to be configured with consistent persistence volume longhorn
# to avoid losing critical data on production
# deployment:
#   kind: DaemonSet

# persistence:
#   enabled: true
#   storageClass: longhorn
