# https://github1s.com/traefik/traefik-helm-chart/blob/HEAD/traefik/values.yaml
# https://blog.tomarrell.com/post/traefik_v2_on_kubernetes
# https://traefik.io/blog/https-on-kubernetes-using-traefik-proxy/

# providers:
#   kubernetesCRD:
#     namespaces:
#       - default
#       - traefik
#       - uat
#       - monitoring
#   kubernetesIngress:
#     allowExternalNameServices: true
#     namespaces:
#       - default
#       - traefik
#       - uat
#       - monitoring

additionalArguments:
  - --certificatesresolvers.letsencrypt.acme.email=youremmail@gmail.com
  - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
  - --certificatesresolvers.letsencrypt.acme.storage=/data/letsencrypt.json
  # - --api.insecure=true
  - --accesslog=true
  - --log.level=DEBUG
  # Please note that this is the staging Let's Encrypt server.
  # Once you get things working, you should remove that whole line altogether.
  - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory

# deployment:
#   kind: DaemonSet

# ports:
#   web:
#     redirectTo: websecure

# service:
#   type: LoadBalancer
#   externalIPs:
#     - 45.155.170.23 # important to have access to dashboard (or see metallb)

# https://doc.traefik.io/traefik/https/tls/#strict-sni-checking
tlsOptions:
  default:
    minVersion: VersionTLS12
    sniStrict: false
    cipherSuites:
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      - TLS_AES_256_GCM_SHA384
      - TLS_AES_128_GCM_SHA256
      - TLS_CHACHA20_POLY1305_SHA256
      - TLS_FALLBACK_SCSV
    curvePreferences:
      - CurveP521
      - CurveP384
  mintls13:
    minVersion: VersionTLS13
