# https://github.com/bitnami/charts/tree/master/bitnami/redis#master-replicas-with-sentinel
global:
  storageClass: microk8s-hostpath
redis:
  password: root
sentinel:
  enabled: true
volumePermissions:
  enabled: true
